version: "3.8"

services:
  app:
    build: .
    restart: always
    network_mode: "host" # 호스트 네트워크 사용 (호스트의 localhost에 접근 가능)
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - CHANNEL_ID_YANOLJA=${CHANNEL_ID_YANOLJA}
      - CHANNEL_ID_NAVER_BOOKING=${CHANNEL_ID_NAVER_BOOKING}
      - CHANNEL_ID_AIRBNB=${CHANNEL_ID_AIRBNB}
      - CHANNEL_ID_YEOGI=${CHANNEL_ID_YEOGI}
      # 호스트에 있는 DB 정보 사용
      - DB_USER=postgres
      - DB_HOST=localhost
      - DB_DATABASE=pension_db
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - API_ENABLE=true
      - API_PORT=8090
      - NODE_ENV=production
      - LOG_LEVEL=info
      - BACKUP_ENABLED=${BACKUP_ENABLED:-false}
      - BACKUP_INTERVAL_DAYS=${BACKUP_INTERVAL_DAYS:-1}
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-30}
    ports:
      - "${API_PORT:-8090}:${API_PORT:-8090}"
    volumes:
      - ./logs:/app/logs:rw
      - ./downloads:/app/downloads:rw
      - ./backups:/app/backups:rw

volumes:
  postgres_data:
